# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:19
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='user'),
        ),
    ]
