# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebook', '0003_auto_20171126_2300'),
        ('member', '0002_auto_20171129_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='imagebook.Post'),
        ),
    ]
