# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import imagebook.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagebook', '0002_auto_20171126_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='', help_text='최대 140자 입력 가능', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=imagebook.models.photo_path),
        ),
    ]
